# Generated by Django 3.2.6 on 2021-08-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.CharField(max_length=12)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=512)),
                ('degree', models.CharField(max_length=256)),
                ('dod', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=512)),
                ('YoE', models.CharField(max_length=20)),
            ],
        ),
    ]
